my_string = input('Введите произвольное количество символов: ')
print(my_string)
print(len(my_string))
print (type(len(my_string)))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(list(my_string)[0])
print(list(my_string)[len(my_string)-1])